### ISSUE TITLE
Labels scroll down the page as canvas is scrolled horizontally

### ISSUE THREAD

**Issue by gingerbeardman** [pipes-digital/pipes#86] opened 2022-02-10 15:13 UTC
See this screen recording for the bug:

https://imgur.com/FgSQorf

Screenshot:
<img width="1080" alt="Screen shot 2022-02-10 at 15 14 20" src="https://user-images.githubusercontent.com/49612/153437192-a9e302d8-47df-4698-ae41-e870a1e80972.png">

**Comment by onli** [comment] 2022-02-10 15:39
Hi @gingerbeardman . Thanks for the report. Which browser is this?

The label scrolling is done by JavaScript, and it's sadly indeed possible that it breaks in other browsers.

**Comment by gingerbeardman** [comment] 2022-02-10 16:08
Hi, this is the very latest Safari 15.3 (17612.4.9.1.5) on macOS 12.2 (21D49)

In other browsers I see different but similar problems...

Chrome:
<img width="1080" alt="Screen shot 2022-02-10 at 16 06 20" src="https://user-images.githubusercontent.com/49612/153447473-d6ff9b98-1262-4028-ad1b-16b82305db8a.png">

Opera
<img width="1080" alt="Screen shot 2022-02-10 at 16 07 34" src="https://user-images.githubusercontent.com/49612/153447645-967fe34c-f313-413e-bfd4-2f19252c8d47.png">

**Comment by onli** [comment] 2022-02-10 22:54
Strange, Chrome I test of course. Safari is hard to test since it's proprietary and not available on Linux, but Chrome should've worked - and I can't reproduce it yet. Could you send me the pipe where this breaks? If you don't want to have it public you could send it by mail to support@pipes.digital.

Also consider testing with Firefox, that's the browser that sees the most testing.

**Comment by gingerbeardman** [comment] 2022-02-10 23:04
pipe 1qWnzvOy

**Comment by gingerbeardman** [comment] 2022-02-10 23:10
Correct pipe is `DNJyxk9a`

**Comment by onli** [comment] 2024-01-09 14:27
I will close here. For now, Safari is out of scope. 

I'm aware that the editor UI is not completely stable and can break with new browser version. One idea to solve this for good would be to re-implement the whole thing with Flutter. While I'm not generally a fan of Flutter for the Web, this canvas here seems like a perfect use case - it can not be done in HTML anyway, and the implementation would be a lot more stable.

**Closed by onli** 2024-01-09 14:27 UTC

**Comment by gingerbeardman** [comment] 2024-01-10 12:54
WebKit is out of scope? 

WebKit 27% of browser market share (Chrome is 59%)
https://www.similarweb.com/browsers/

**Comment by onli** [comment] 2024-01-10 12:56
I'm simply not able to test with Safari. But we can also keep this open and ask for help instead? If someone wanted to provide patches for the editor javascript/css, I'd happily merge them!
